  services:
    frontend:
      build:
        context: .
        dockerfile: frontend/Dockerfile
      ports:
        - "3000:80"
      depends_on:
        - backend

    backend:
      build:
        context: .
        dockerfile: backend/Dockerfile
      ports:
        - "5000:5000"
